version: '3'

services:
  backend:
    build: ./Backend
    ports:
      - 8000:8000
  frontend:
   build:
     args:
       API_URL: http://127.0.0.1:8000/api/
   ports:
          - 3000:3000






 
      



