version: '3.4'


services:
  postgres_db:
    container_name: postgres_db
    image:
      postgres:13.4-alpine
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "20m"
    env_file:
      - envs/database.env
    restart:
      on-failure
    networks:
      - pgdb


  backend:
    container_name: backend
    build:
      context: backend/
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 -w 2
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    env_file:
      - envs/database.env
      - envs/backend.env
    restart:
      on-failure
    networks:
      - pgdb
      - front_back

  frontend:
    build:
      context: frontend/
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - front_back
    volumes:
      - ./frontend/:/frontend
    restart:
      on-failure

  nginx:
    container_name: nginx
    image: nginx:custom
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - static:/usr/src/app/static
    depends_on:
      - frontend

networks:
  pgdb:
  front_back:


volumes:
  static:
    external: false